name: ci
on:
  pull_request:
  push:
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  x86_64-linux-debug:
    timeout-minutes: 420
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ninja-build
        run: apt update && apt install ninja-build
      - name: Build and Test
        run: sh ci/x86_64-linux-debug.sh
